on:
  push:
    branches:
      - master
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['unit-3.6', 'unit-3.7', 'unit-pypy3']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python -m pip install --upgrade nox
      - run: python -m nox -s ${{ matrix.python }}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m nox -s docs
      - run: python -m nox -s doctest
